name: Deploy SQL Server Docker - DEV

on:
  push:
    branches:
      - dev
    paths:
      - "env/dev/**"

jobs:
  terraform-dev:
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set SA Password
        run: |
          echo "sa_password=${{ secrets.DEV_SQL_SA_PASSWORD }}" > env/dev/terraform.tfvars

      - name: Terraform Init & Apply
        working-directory: env/dev
        run: |
          terraform init
          terraform apply -auto-approve


