name: Deploy SQL Server Docker - PROD1

on:
  push:
    branches:
      - main
    paths:
      - "env/prod/**"

jobs:
  terraform-prod:
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Terraform Init & Apply (PROD)
        working-directory: env/prod
        run: |
          terraform init
          terraform apply -auto-approve -var="sa_password=${{ secrets.DEV_SQL_SA_PASSWORD }}"
